import * as core from '@actions/core';
import type {
	CommentContext,
	QuestionDetectionConfig,
} from './types';

// ============================================================================
// Constants
// ============================================================================

const DEFAULT_QUESTION_KEYWORDS = [
	'?',
	'what',
	'how',
	'why',
	'can you',
	'could you',
	'would you',
	'please explain',
	'help me understand',
	'what do you mean',
	'why not',
	'can you clarify',
	'not sure',
	'confused',
	'unclear',
];

const AI_REVIEW_MARKER_PATTERN = /<!-- ai-review-id:([a-f0-9]{12}) -->/;
const AI_REPLY_MARKER_PATTERN = /<!-- ai-reply -->/;

// ============================================================================
// Comment Detection Functions
// ============================================================================

/**
 * Check if a comment contains a question
 */
export function isQuestionComment(
	commentBody: string,
	config: QuestionDetectionConfig
): boolean {
	if (!config.enabled) {
		return true;
	}

	const lowerBody = commentBody.toLowerCase();

	// Check for question mark
	if (lowerBody.includes('?')) {
		return true;
	}

	// Check for question keywords
	for (const keyword of config.keywords) {
		if (lowerBody.includes(keyword)) {
			return true;
		}
	}

	core.debug('Comment does not appear to be a question');
	return false;
}

/**
 * Check if a comment was generated by AI (has ai-review-id marker)
 */
export function isAiComment(commentBody: string): boolean {
	return AI_REVIEW_MARKER_PATTERN.test(commentBody);
}

/**
 * Extract the ai-review-id from a comment
 */
export function extractAiReviewId(commentBody: string): string | null {
	const match = commentBody.match(AI_REVIEW_MARKER_PATTERN);
	return match ? match[1] : null;
}

/**
 * Check if a comment is an AI-generated reply
 */
export function isAiReply(commentBody: string): boolean {
	return AI_REPLY_MARKER_PATTERN.test(commentBody);
}

/**
 * Check if the comment author is a bot
 */
export function isBotComment(authorType: string | undefined): boolean {
	return authorType === 'Bot';
}

/**
 * Check if we should trigger a reply
 * Conditions:
 * 1. Comment is not from a bot
 * 2. Comment is not an AI reply itself
 * 3. Comment is a question (if detection enabled)
 */
export function shouldTriggerReply(
	commentBody: string,
	authorType: string | undefined,
	questionDetectionConfig: QuestionDetectionConfig
): boolean {
	// Skip bot comments
	if (isBotComment(authorType)) {
		core.debug('Skipping bot comment');
		return false;
	}

	// Skip AI replies (avoid infinite loops)
	if (isAiReply(commentBody)) {
		core.debug('Skipping AI reply comment');
		return false;
	}

	// Check if it's a question
	if (!isQuestionComment(commentBody, questionDetectionConfig)) {
		return false;
	}

	return true;
}

/**
 * Create default question detection config
 */
export function createDefaultQuestionDetectionConfig(
	enabled: boolean = true
): QuestionDetectionConfig {
	return {
		enabled,
		keywords: DEFAULT_QUESTION_KEYWORDS,
	};
}

