export const SQL_RULES = [
	'PostgreSQL/MySQL specifics:',
	'SQL injection:',
	'- never concatenate user input into raw queries; use parameterized queries / ORM safe APIs',
	'- flag string interpolation or template literals in knex.raw, prisma.$queryRawUnsafe, drizzle sql tag, typeorm query()',
	'- ORM raw fallback (prisma.$queryRaw, drizzle.execute, typeorm.manager.query) must use bound params',
	'Indexing:',
	'- new WHERE/JOIN/filter columns without index → flag as performance',
	'- SELECT * without LIMIT → flag, especially on large tables',
	'- missing WHERE on UPDATE/DELETE → critical correctness',
	'- low-selectivity index removed or predicate changed → verify query patterns',
	'- partial index predicate must match actual queries; check LIKE prefix vs full scan',
	'Migration safety:',
	'- ALTER TABLE on large table without CONCURRENTLY / online DDL → lock duration risk',
	'- CREATE INDEX must be CONCURRENTLY (Postgres) on production tables',
	'- DROP COLUMN: verify no app code still references it (cross-stack grep)',
	'- RENAME column/table → coordination risk (deploy ordering)',
	'- irreversible DDL (DROP, TRUNCATE) without backwards-compatible step → flag',
	'- NOT NULL added without DEFAULT/backfill on existing rows → will fail on large tables',
	'ORM-specific:',
	'- Prisma: nested include deeper than 2 levels → N+1 risk; prefer select with explicit depth',
	'- Drizzle: with:{} chain depth check; unbounded with without limit',
	'- TypeORM: relations:[] without loadEagerRelations:false can silently join too much',
	'- Knex/raw: string interpolation detected → SQL injection',
	'Pool/timeout:',
	'- pool size vs expected concurrency; missing statement_timeout / idleTimeout',
	'- connection not released in finally → leak under errors',
	'- long-running query without timeout on user-facing path',
	'MySQL specifics:',
	'- implicit type conversion (VARCHAR = INT) bypasses index → flag',
	'- GROUP BY with non-aggregated columns under ONLY_FULL_GROUP_BY',
	'- missing FOR UPDATE / locking read when transaction expects it',
].join('\n');
