name: 'AI Code Review'
description: 'Uses OpenAI to review pull requests and suggest improvements'
author: 'niko0xdev'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  openai-api-key:
    description: 'OpenAI API key for code review'
    required: true
  openai-base-url:
    description: 'Custom OpenAI API base URL (optional)'
    required: false
  openai-model:
    description: 'OpenAI model to use for review'
    required: false
    default: 'gpt-4'
  review-prompt:
    description: 'Custom prompt for OpenAI review'
    required: false
    default: 'Focus on correctness, code quality, security, performance, test coverage, and best practices. Provide actionable, line-specific feedback whenever possible.'
  max-files:
    description: 'Maximum number of files to review'
    required: false
    default: '10'
  exclude-patterns:
    description: 'Comma-separated list of file patterns to exclude from review'
    required: false
    default: '*.md,*.txt,*.json,*.yml,*.yaml'
  auto-approve-when-resolved:
    description: 'If true, approve the pull request when all AI-generated review threads are resolved'
    required: false
    default: 'false'
  min-severity:
    description: 'Minimum severity level for comments (info, low, medium, high)'
    required: false
    default: 'info'

outputs:
  review-summary:
    description: 'Summary of the code review'

runs:
  using: 'node20'
  main: 'dist/index.js'
